### PR TITLE
upgrade to mermaid 10.8.0

### PR DESCRIPTION
**Pull request by ProbablePrime**
This PR upgrades: https://github.com/SemanticMediaWiki/Mermaid/pull/102 from using 10.6.x to 10.8.0.

I had to manually patch a couple of minification issues in the resources file, that someone more knowledgeable in the resource loader might have to handle later. See comments on: https://github.com/SemanticMediaWiki/Mermaid/pull/102 for more info.

I also correct the "&gt" issue which appears to be an unnecessary html special characters encoding.

It is live on: https://wiki.resonite.com/Test:Mermaid for you to see, using some of the latest syntax in Mermaid which I needed.

### CODE REVIEW

**Comment by lyrixn** [comment]
Would it be a lot of trouble to bump this to 11.4.0?

**Comment by sneakers-the-rat** [comment]
probably not, just replace the minified js file, but one would want to do that in the upstream repo rather than this one (which is a fork). Really what the extension should do is allow you to provide your own path to a local mermaid dist so you can update on your own without needing to wait for the extension, but it aint mine ;)

**Comment by lyrixn** [comment]
Oh. The reason why I asked, is because @ProbablePrime had mentioned they had to manually patch the minified file, so my understanding was that it's not that easy.

**Comment by sneakers-the-rat** [comment]
idk! give it a shot :)

**Pull request merged**
